# Generated by Django 3.1.4 on 2021-07-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_struksold'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomorStrukSoldTerakhir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_struk', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='struksold',
            name='geprek',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='struksold',
            name='level_0',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='struksold',
            name='level_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='struksold',
            name='level_2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='struksold',
            name='level_3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='struksold',
            name='level_4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='struksold',
            name='level_5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='struksold',
            name='level_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='struksold',
            name='status',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
