# Generated by Django 3.1.4 on 2021-07-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0004_auto_20210706_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NomorStrukSoldTerakhir',
        ),
        migrations.DeleteModel(
            name='StrukSold',
        ),
    ]
