# Generated by Django 3.1.4 on 2021-07-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0005_auto_20210706_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomorStrukSoldTerakhir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_struk', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='StrukSold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_struk', models.CharField(max_length=80)),
                ('nama_cabang', models.CharField(max_length=80)),
                ('waktu_struk', models.DateTimeField(verbose_name='Waktu Struk')),
                ('status', models.CharField(max_length=80, null=True)),
                ('jumlah_ayam', models.IntegerField(default=0)),
                ('jumlah_chicken_skin', models.IntegerField(default=0, null=True)),
                ('jumlah_paper_cost_takeaway_l', models.IntegerField(default=0, null=True)),
                ('jumlah_paper_cost_takeaway_m', models.IntegerField(default=0, null=True)),
                ('jumlah_paper_cost_takeaway_paper_bag', models.IntegerField(default=0, null=True)),
                ('jumlah_paper_cost_dine_in_paper_tray', models.IntegerField(default=0, null=True)),
                ('jumlah_topping_crisbar', models.IntegerField(default=0, null=True)),
                ('jumlah_topping_saus_gravy', models.IntegerField(default=0, null=True)),
                ('jumlah_topping_matah', models.IntegerField(default=0, null=True)),
                ('jumlah_topping_mamah', models.IntegerField(default=0, null=True)),
                ('jumlah_topping_tomat', models.IntegerField(default=0, null=True)),
                ('jumlah_topping_manis', models.IntegerField(default=0, null=True)),
                ('jumlah_topping_goang', models.IntegerField(default=0, null=True)),
                ('jumlah_topping_keju', models.IntegerField(default=0, null=True)),
                ('jumlah_tahu_crispy', models.IntegerField(default=0, null=True)),
                ('jumlah_tempe_crispy', models.IntegerField(default=0, null=True)),
                ('jumlah_terong_crispy', models.IntegerField(default=0, null=True)),
                ('jumlah_telur_sayur', models.IntegerField(default=0, null=True)),
                ('jumlah_kol_crispy', models.IntegerField(default=0, null=True)),
                ('jumlah_kerupuk', models.IntegerField(default=0, null=True)),
                ('jumlah_sigulmer_manis_biscuit', models.IntegerField(default=0, null=True)),
                ('jumlah_perkedel', models.IntegerField(default=0, null=True)),
                ('jumlah_nasi_dine_in', models.IntegerField(default=0, null=True)),
                ('jumlah_es_teh_dine_in', models.IntegerField(default=0, null=True)),
                ('jumlah_lemon_tea_dine_in', models.IntegerField(default=0, null=True)),
                ('jumlah_milo_dine_in', models.IntegerField(default=0, null=True)),
                ('jumlah_orange_dine_in', models.IntegerField(default=0, null=True)),
                ('jumlah_nasi_takeaway', models.IntegerField(default=0, null=True)),
                ('jumlah_es_teh_takeaway', models.IntegerField(default=0, null=True)),
                ('jumlah_lemon_tea_takeaway', models.IntegerField(default=0, null=True)),
                ('jumlah_milo_takeaway', models.IntegerField(default=0, null=True)),
                ('jumlah_orange_takeaway', models.IntegerField(default=0, null=True)),
                ('jumlah_air_mineral', models.IntegerField(default=0, null=True)),
                ('jumlah_wings', models.IntegerField(default=0, null=True)),
                ('level_0', models.IntegerField(default=0, null=True)),
                ('level_1', models.IntegerField(default=0, null=True)),
                ('level_2', models.IntegerField(default=0, null=True)),
                ('level_3', models.IntegerField(default=0, null=True)),
                ('level_4', models.IntegerField(default=0, null=True)),
                ('level_5', models.IntegerField(default=0, null=True)),
                ('level_max', models.IntegerField(default=0, null=True)),
                ('geprek', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
