# Generated by Django 3.1.4 on 2021-07-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rm_app', '0005_auto_20210719_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_po', models.CharField(max_length=20)),
                ('nama_pic', models.CharField(max_length=50, null=True)),
                ('nomor_pic', models.CharField(max_length=50, null=True)),
                ('alamat', models.CharField(max_length=100, null=True)),
                ('tanggal_po', models.DateField(null=True)),
                ('profil_pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rm_app.profilpengguna')),
            ],
        ),
        migrations.CreateModel(
            name='StatusPurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=70)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='BarangPurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_item', models.CharField(max_length=30)),
                ('jumlah_order', models.IntegerField()),
                ('satuan', models.CharField(max_length=30)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='BarangDiterima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=150)),
                ('jumlah_diterima', models.IntegerField()),
                ('diterima_sebenarnya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_order.barangpurchaseorder')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order.purchaseorder')),
            ],
        ),
    ]
