# Generated by Django 3.1.4 on 2021-03-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210304_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugasproyek',
            name='archive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tugasrutin',
            name='archive',
            field=models.BooleanField(null=True),
        ),
    ]
