# Generated by Django 3.1.4 on 2021-03-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210309_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='isitugasrutin',
            name='ketuntasan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tugasproyek',
            name='ketuntasan',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
