# Generated by Django 3.1.4 on 2021-03-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210309_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeSp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_periode', models.CharField(max_length=100)),
                ('tahun', models.IntegerField()),
                ('awal_periode', models.DateTimeField(verbose_name='Awal periode')),
                ('akhir_periode', models.DateTimeField(verbose_name='Akhir Periode')),
                ('dieksekusi', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='isitugasrutin',
            name='link_bukti',
            field=models.CharField(default='#', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='KenaSp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('berakhir_pada', models.DateTimeField(verbose_name='Berakhir pada')),
                ('keaktifan', models.BooleanField(default=True)),
                ('periode_sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.periodesp')),
            ],
        ),
    ]
