# Generated by Django 3.1.4 on 2021-04-02 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_averagecheck_datastruk_nomorstrukterakhir'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=50)),
                ('awal_periode', models.DateField()),
                ('akhir_periode', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OmsetBulan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omset_bulan_ini', models.IntegerField()),
                ('omset_bulan_sebelumnya', models.IntegerField()),
                ('target_omset', models.IntegerField()),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.periodekerja')),
            ],
        ),
    ]
