# Generated by Django 3.1.4 on 2021-04-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_omsetbulan_periodekerja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_operasional', models.TimeField()),
                ('nama', models.CharField(max_length=100)),
                ('media_penyampaian_complain', models.CharField(max_length=100)),
                ('nomor_kontak', models.CharField(max_length=30)),
                ('complaint', models.TextField(max_length=1000)),
                ('handling', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('Kualitas Produk', 'Kualitas Produk'), ('Kebersihan', 'Kebersihan'), ('Pelayanan', 'Pelayanan'), ('Tidak Lengkap', 'Tidak Lengkap'), ('Lainnya', 'Lainnya')], max_length=100, null=True)),
                ('cabang', models.CharField(choices=[('Antapani', 'Antapani'), ('Cisitu', 'Cisitu'), ('Jatinangor', 'Jatinangor'), ('Metro', 'Metro'), ('Sukapura', 'Sukapura'), ('Sukabirus', 'Sukabirus'), ('Sukajadi', 'Sukajadi'), ('Unjani', 'Unjani')], max_length=100)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
