# Generated by Django 3.1.4 on 2021-04-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_mysteryguest'),
    ]

    operations = [
        migrations.CreateModel(
            name='KepuasanPelanggan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('google_antapani', models.FloatField()),
                ('google_cisitu', models.FloatField()),
                ('google_jatinangor', models.FloatField()),
                ('google_metro', models.FloatField()),
                ('google_sukabirus', models.FloatField()),
                ('google_sukapura', models.FloatField()),
                ('google_sukajadi', models.FloatField()),
                ('google_unjani', models.FloatField()),
                ('gofood_antapani', models.FloatField()),
                ('gofood_cisitu', models.FloatField()),
                ('gofood_jatinangor', models.FloatField()),
                ('gofood_metro', models.FloatField()),
                ('gofood_sukabirus', models.FloatField()),
                ('gofood_sukapura', models.FloatField()),
                ('gofood_sukajadi', models.FloatField()),
                ('gofood_unjani', models.FloatField()),
                ('grabfood_antapani', models.FloatField()),
                ('grabfood_cisitu', models.FloatField()),
                ('grabfood_jatinangor', models.FloatField()),
                ('grabfood_metro', models.FloatField()),
                ('grabfood_sukabirus', models.FloatField()),
                ('grabfood_sukapura', models.FloatField()),
                ('grabfood_sukajadi', models.FloatField()),
                ('grabfood_unjani', models.FloatField()),
                ('survei_antapani', models.FloatField()),
                ('survei_cisitu', models.FloatField()),
                ('survei_jatinangor', models.FloatField()),
                ('survei_metro', models.FloatField()),
                ('survei_sukabirus', models.FloatField()),
                ('survei_sukapura', models.FloatField()),
                ('survei_sukajadi', models.FloatField()),
                ('survei_unjani', models.FloatField()),
            ],
        ),
    ]
