# Generated by Django 3.1.4 on 2021-04-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_assemblyproduct_tanggalweekendweekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyproduct',
            name='kategori',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='nama',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
