# Generated by Django 3.1.4 on 2021-04-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210427_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='PemakaianAyam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('pemakaian_ayam', models.IntegerField(default=0)),
                ('pemakaian_ayam_antapani', models.IntegerField(default=0)),
                ('pemakaian_ayam_jatinangor', models.IntegerField(default=0)),
                ('pemakaian_ayam_metro', models.IntegerField(default=0)),
                ('pemakaian_ayam_sukapura', models.IntegerField(default=0)),
                ('pemakaian_ayam_sukabirus', models.IntegerField(default=0)),
                ('pemakaian_ayam_unjani', models.IntegerField(default=0)),
                ('pemakaian_ayam_cisitu', models.IntegerField(default=0)),
                ('pemakaian_ayam_sukajadi', models.IntegerField(default=0)),
                ('dieksekusi', models.BooleanField(default=False)),
            ],
        ),
    ]
