# Generated by Django 3.1.4 on 2021-05-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_hariproduksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabanist',
            name='l1',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l10',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l11',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l12',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l13',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l14',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l15',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l16',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l17',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l18',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l19',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l2',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l20',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l21',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l22',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l23',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l24',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l3',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l4',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l5',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l6',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l7',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l8',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='l9',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m1',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m10',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m11',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m12',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m13',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m14',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m15',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m16',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m17',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m18',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m19',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m2',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m20',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m21',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m22',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m23',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m24',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m3',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m4',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m5',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m6',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m7',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m8',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jawabanist',
            name='m9',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
