# Generated by Django 3.1.4 on 2021-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210503_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyproduct',
            name='chicken_skin',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pemakaianayam',
            name='pemakaian_chicken_skin',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pemakaianayam',
            name='pemakaian_chicken_skin_antapani',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pemakaianayam',
            name='pemakaian_chicken_skin_cisitu',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pemakaianayam',
            name='pemakaian_chicken_skin_jatinangor',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pemakaianayam',
            name='pemakaian_chicken_skin_metro',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pemakaianayam',
            name='pemakaian_chicken_skin_sukabirus',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pemakaianayam',
            name='pemakaian_chicken_skin_sukajadi',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pemakaianayam',
            name='pemakaian_chicken_skin_sukapura',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pemakaianayam',
            name='pemakaian_chicken_skin_unjani',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
