# Generated by Django 3.1.4 on 2021-05-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210508_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyproduct',
            name='air_mineral',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='es_teh_dine_in',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='es_teh_takeaway',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='kerupuk',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='kol_crispy',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='lemon_tea_dine_in',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='lemon_tea_takeaway',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='milo_dine_in',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='milo_takeaway',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='nasi_dine_in',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='nasi_takeaway',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='orange_dine_in',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='orange_takeaway',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='paper_cost_dine_in_paper_tray',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='paper_cost_takeaway_l',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='paper_cost_takeaway_m',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='paper_cost_takeaway_paper_bag',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='perkedel',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='sigulmer_manis_biscuit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='tahu_crispy',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='telur_sayur',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='tempe_crispy',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='terong_crispy',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='topping_crisbar',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='topping_goang',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='topping_keju',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='topping_mamah',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='topping_manis',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='topping_matah',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='topping_saus_gravy',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assemblyproduct',
            name='topping_tomat',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
