# Generated by Django 3.1.4 on 2021-06-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20210523_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabangnya', models.CharField(max_length=70)),
                ('onrollnya', models.IntegerField()),
                ('target_labour', models.FloatField()),
            ],
        ),
    ]
