# Generated by Django 3.1.4 on 2021-06-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_onroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='kepuasanpelanggan',
            name='gofood_kopo',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='kepuasanpelanggan',
            name='google_kopo',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='kepuasanpelanggan',
            name='grabfood_kopo',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='kepuasanpelanggan',
            name='survei_kopo',
            field=models.FloatField(default=0, null=True),
        ),
    ]
