# Generated by Django 3.1.4 on 2021-05-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produksiayam',
            name='jam_10_ayam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produksiayam',
            name='jam_10_lemontea',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produksiayam',
            name='jam_10_milo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produksiayam',
            name='jam_10_nasi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produksiayam',
            name='jam_10_orange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produksiayam',
            name='jam_10_teh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produksiayam',
            name='jam_9_ayam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produksiayam',
            name='jam_9_lemontea',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produksiayam',
            name='jam_9_milo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produksiayam',
            name='jam_9_nasi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produksiayam',
            name='jam_9_orange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produksiayam',
            name='jam_9_teh',
            field=models.IntegerField(default=0),
        ),
    ]
