# Generated by Django 3.1.4 on 2021-06-25 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm_app', '0002_auto_20210519_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenTanggal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('cabang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AbsenKaryawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=10)),
                ('absen', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Libur', 'Libur'), ('Cuti', 'Cuti'), ('Alpha', 'Alpha'), ('WFH', 'WFH')], max_length=10)),
                ('tanggal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rm_app.absentanggal')),
            ],
        ),
    ]
