# Generated by Django 3.1.4 on 2021-07-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm_app', '0004_shiftoperasional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpengguna',
            name='alamat',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profilpengguna',
            name='nama',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profilpengguna',
            name='nomor_hp',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
