# Generated by Django 3.1.4 on 2021-07-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStruk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100)),
                ('receipt_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('receipt_date', models.DateTimeField()),
                ('total_money', models.IntegerField()),
                ('total_tax', models.IntegerField()),
                ('store_id', models.CharField(max_length=170)),
                ('dining_option', models.CharField(max_length=100)),
                ('payments', models.CharField(max_length=100)),
            ],
        ),
    ]
