# Generated by Django 3.1.4 on 2021-06-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('item', models.ManyToManyField(blank=True, to='layermanager.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Varian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('harga', models.IntegerField(default=0)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layermanager.modifier')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layermanager.kategori'),
        ),
        migrations.CreateModel(
            name='Harga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Harga', max_length=200)),
                ('harga_dinein', models.IntegerField(default=0)),
                ('harga_takeaway', models.IntegerField(default=0)),
                ('harga_gofood', models.IntegerField(default=0)),
                ('harga_grabfood', models.IntegerField(default=0)),
                ('harga_shopeefood', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layermanager.item')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layermanager.layer')),
            ],
        ),
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layermanager.layer')),
            ],
        ),
    ]
